batch:
  - type: mdb2fbx
    settings:
      exporter:
        texture-conversion:
          format: png
        skip-nodes:
          if-name-contains:
            - Shadowbone
            - shadowbone
        logging:
          level: DEBUG
        unit-conversion-factor: 100.0
      input:
        path: "E:/projects/the_witcher/content_pipeline/unbiffed"
      logging:
        level: DEBUG
      destination:
        model:
          destination: "E:/projects/the_witcher/export_dest/model"
          organization: all-in-one-place
        animation:
          destination: "E:/projects/the_witcher/export_dest/animation"
          organization: all-in-one-place
        texture:
          organization: with-model
